
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.1.0
 * Query Engine version: ab635e6b9d606fa5c8fb8b1a7f909c3c3c1c98ba
 */
Prisma.prismaVersion = {
  client: "7.1.0",
  engine: "ab635e6b9d606fa5c8fb8b1a7f909c3c3c1c98ba"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  state: 'state',
  googleOAuthId: 'googleOAuthId',
  password: 'password',
  salt: 'salt',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  settingsId: 'settingsId',
  profilePictureId: 'profilePictureId'
};

exports.Prisma.UserSettingsScalarFieldEnum = {
  id: 'id',
  notificationsEnabled: 'notificationsEnabled',
  language: 'language',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FileScalarFieldEnum = {
  id: 'id',
  name: 'name',
  path: 'path',
  mimeType: 'mimeType',
  size: 'size',
  access: 'access',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FilePermissionScalarFieldEnum = {
  fileId: 'fileId',
  userId: 'userId',
  permission: 'permission',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RefreshTokenScalarFieldEnum = {
  refreshTokenId: 'refreshTokenId',
  token: 'token',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastUsedAt: 'lastUsedAt',
  expiresAt: 'expiresAt',
  valid: 'valid',
  rememberUser: 'rememberUser',
  userId: 'userId'
};

exports.Prisma.AccessTokenScalarFieldEnum = {
  accessTokenId: 'accessTokenId',
  token: 'token',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastUsedAt: 'lastUsedAt',
  expiresAt: 'expiresAt',
  valid: 'valid',
  refreshTokenId: 'refreshTokenId',
  userId: 'userId'
};

exports.Prisma.TokenScalarFieldEnum = {
  id: 'id',
  type: 'type',
  userId: 'userId',
  hashedSecret: 'hashedSecret',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  expiresAt: 'expiresAt',
  valid: 'valid'
};

exports.Prisma.EloHistoryScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  gameId: 'gameId',
  playerId: 'playerId',
  eloBefore: 'eloBefore',
  eloAfter: 'eloAfter',
  gamesPlayedBefore: 'gamesPlayedBefore',
  gamesPlayedAfter: 'gamesPlayedAfter'
};

exports.Prisma.OpenSkillHistoryScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  gameId: 'gameId',
  playerId: 'playerId',
  muBefore: 'muBefore',
  muAfter: 'muAfter',
  sigmaBefore: 'sigmaBefore',
  sigmaAfter: 'sigmaAfter',
  ordinalBefore: 'ordinalBefore',
  ordinalAfter: 'ordinalAfter'
};

exports.Prisma.GameScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  playerAId: 'playerAId',
  playerBId: 'playerBId',
  gameStart: 'gameStart',
  gameEnd: 'gameEnd',
  bullOffWinnerId: 'bullOffWinnerId',
  winnerId: 'winnerId',
  loserId: 'loserId',
  type: 'type',
  checkoutMode: 'checkoutMode'
};

exports.Prisma.GameStatisticsIndividualScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  gameId: 'gameId',
  playerId: 'playerId',
  wonBullOff: 'wonBullOff',
  averageScore: 'averageScore',
  averageUntilFirstPossibleFinish: 'averageUntilFirstPossibleFinish',
  throwsOnDouble: 'throwsOnDouble'
};

exports.Prisma.GameVisitScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  gameId: 'gameId',
  playerId: 'playerId',
  visitNumber: 'visitNumber',
  throw1: 'throw1',
  throw1Multiplier: 'throw1Multiplier',
  throw2: 'throw2',
  throw2Multiplier: 'throw2Multiplier',
  throw3: 'throw3',
  throw3Multiplier: 'throw3Multiplier',
  totalScored: 'totalScored',
  remainingScoreBefore: 'remainingScoreBefore',
  remainingScoreAfter: 'remainingScoreAfter',
  outcome: 'outcome'
};

exports.Prisma.PlayerOfTheWeekScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  playerId: 'playerId',
  weekStart: 'weekStart',
  eloDifference: 'eloDifference',
  openSkillDifference: 'openSkillDifference',
  averageScore: 'averageScore',
  scoringAverage: 'scoringAverage',
  numberOfGames: 'numberOfGames'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.UserState = exports.$Enums.UserState = {
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  COMPLETE: 'COMPLETE',
  INACTIVE: 'INACTIVE'
};

exports.Language = exports.$Enums.Language = {
  EN: 'EN',
  DE: 'DE'
};

exports.FileAccess = exports.$Enums.FileAccess = {
  PRIVATE: 'PRIVATE',
  PUBLIC: 'PUBLIC'
};

exports.FilePermissionType = exports.$Enums.FilePermissionType = {
  DENIED: 'DENIED',
  READ: 'READ',
  WRITE: 'WRITE',
  DELETE: 'DELETE',
  CREATOR: 'CREATOR'
};

exports.TokenType = exports.$Enums.TokenType = {
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
  CONNECT_GOOGLE_ACCOUNT: 'CONNECT_GOOGLE_ACCOUNT'
};

exports.GameType = exports.$Enums.GameType = {
  X301: 'X301',
  X501: 'X501'
};

exports.GameCheckoutMode = exports.$Enums.GameCheckoutMode = {
  SINGLE_OUT: 'SINGLE_OUT',
  DOUBLE_OUT: 'DOUBLE_OUT',
  MASTER_OUT: 'MASTER_OUT'
};

exports.GameVisitOutcome = exports.$Enums.GameVisitOutcome = {
  BUSTED: 'BUSTED',
  HIT: 'HIT',
  MISS: 'MISS'
};

exports.Prisma.ModelName = {
  User: 'User',
  UserSettings: 'UserSettings',
  File: 'File',
  FilePermission: 'FilePermission',
  RefreshToken: 'RefreshToken',
  AccessToken: 'AccessToken',
  Token: 'Token',
  EloHistory: 'EloHistory',
  OpenSkillHistory: 'OpenSkillHistory',
  Game: 'Game',
  GameStatisticsIndividual: 'GameStatisticsIndividual',
  GameVisit: 'GameVisit',
  PlayerOfTheWeek: 'PlayerOfTheWeek'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
