export const nameEmailMapping: Record<string, string> = {
    'Kai Adrian Münzberg': 'adrian.muenzberg@pickware.de',
    'Alexandra Schäfer': 'alexandra.schaefer@pickware.de',
    'Ann-Kristin Martin': 'ann-kristin.martin@pickware.de',
    'Antonio Kuprešak': 'antonio.kupresak@pickware.de',
    'Bartolomeo Müller': 'bartolomeo.mueller@pickware.de',
    'Benedikt Brunner': 'benedikt.brunner@pickware.de',
    'Cedric Engler': 'cedric.engler@pickware.de',
    'Christian Juner': 'christian.juner@pickware.de',
    'Clemens Brockschmidt': 'clemens.brockschmidt@pickware.de',
    'Cloud Ops': 'cloud-ops@pickware.de',
    'Contacts Pickware': 'contacts@pickware.de',
    'Dennis Holzamer': 'dennis.holzamer@pickware.de',
    'Domenic Gerhold': 'domenic.gerhold@pickware.de',
    'Elias Esposito': 'elias.esposito@pickware.de',
    'Erik Forss': 'erik.forss@pickware.de',
    'Fabian Berres': 'fabian.berres@pickware.de',
    'Florian Faatz': 'florian.faatz@pickware.de',
    'Get Pickware': 'sales@getpickware.com',
    'Hannes Wernery': 'hannes.wernery@pickware.de',
    'Jan Petto': 'jan.petto@pickware.de',
    'Jan Scholtes': 'jan.scholtes@pickware.de',
    'Jan-Philipp Rogge': 'jan-philipp.rogge@pickware.de',
    'Jannik Jochem': 'jannik.jochem@pickware.de',
    'Jannik Schaper': 'jannik.schaper@pickware.de',
    'Jessica Pleier': 'jessica.pleier@pickware.de',
    'Johannes Rübsam': 'johannes.ruebsam@pickware.de',
    'John Sorial': 'john.sorial@pickware.de',
    'Jonathan Schad': 'jonathan.schad@pickware.de',
    'Julia Schütz': 'julia.schuetz@pickware.de',
    'Julian Drauz': 'julian.drauz@pickware.de',
    'Lars Emig': 'lars.emig@pickware.de',
    'Laurin Lehr': 'laurin.lehr@pickware.de',
    'Lea Finke': 'lea.finke@pickware.de',
    'Liane Becker': 'liane.becker@pickware.de',
    'Live Demo': 'livedemo@pickware.de',
    'Luca Schlomski': 'luca.schlomski@pickware.de',
    'Manuel Kress': 'manuel.kress@pickware.de',
    'Mario Nowak': 'mario.nowak@pickware.de',
    'Mark Viertel': 'mark.viertel@pickware.de',
    'Marlon Haas': 'marlon.haas@pickware.de',
    'Martina Mrkonjic': 'martina.mrkonjic@pickware.de',
    'Marvin Schneemann': 'marvin.schneemann@pickware.de',
    'Maurice Calmano': 'maurice.calmano@pickware.de',
    'Maximilian Oster': 'maximilian.oster@pickware.de',
    'Maximilian Rüsch': 'maximilian.ruesch@pickware.de',
    'Mia Porteous': 'mia.porteous@pickware.de',
    'Michael Haas': 'michael.haas@pickware.de',
    'Miriam Faßbender': 'miriam.fassbender@pickware.de',
    'Mirka Henckes': 'mirka.henckes@pickware.de',
    'Nicolas Zander': 'nicolas.zander@pickware.de',
    'Pascal Buhr': 'pascal.buhr@pickware.de',
    'Pascal Paul': 'pascal.paul@pickware.de',
    'Paul von Allwörden': 'paul.von.allwoerden@pickware.de',
    'People & Culture Team': 'people@pickware.de',
    'Philipp Seemann': 'philipp.seemann@pickware.de',
    'Pickware ': 'support@pickware.de',
    'Pickware Account': 'account@pickware.de',
    'Pickware Admin': 'admin@pickware.de',
    'Pickware Business Meeting': 'business.meeting@pickware.de',
    'Pickware Jobs': 'jobs@pickware.de',
    'Pickware Kino Meeting': 'kino.meeting@pickware.de',
    'Pickware Lounge Meeting': 'lounge.meeting@pickware.de',
    'Pickware Marketing': 'marketing@pickware.de',
    'Pickware Partner': 'partner@pickware.de',
    'Pickware Sales': 'sales@pickware.de',
    'Pickware Team': 'team@pickware.de',
    'Pickware Tutorials': 'tutorials@pickware.de',
    'Rebecca Falkenburg': 'rebecca.falkenburg@pickware.de',
    'Robin Lanz': 'robin.lanz@pickware.de',
    'Samuel Vogel': 'samuel.vogel@pickware.de',
    'Sarah Brenner': 'sarah.brenner@pickware.de',
    'Sebastian Nieraad': 'sebastian.nieraad@pickware.de',
    'Simge Karaduman': 'simge.karaduman@pickware.de',
    'Stefan Heppenheimer': 'stefan.heppenheimer@pickware.de',
    'Sven Münnich': 'sven.muennich@pickware.de',
    'Tanja Cremer': 'tanja.cremer@pickware.de',
    'Till Grimminger': 'till.grimminger@pickware.de',
    'Tristan Eckart': 'tristan.eckart@pickware.de',
    'Tristan Tisch': 'tristan.tisch@pickware.de',
    'Yannik Ehrhardt': 'yannik.ehrhardt@pickware.de',
    'Youness Marzouki': 'youness.marzouki@pickware.de',
    'Luca kleine Hillmann': 'luca.kleine.hillmann@pickware.de',
    'Hannibal Wissing': 'hannibal.wissing@pickware.de',
    'Sebastian Volker Nieraad': 'sebastian.nieraad@pickware.de',
    'Norman Schirg': 'norman.schirg@pickware.de',
    'Marco Weßel': 'marco.wessel@pickware.de',
    'Madlen Springer': 'madlen.springer@pickware.de',
    'Felix Meiser': 'felix.meiser@pickware.de',
    'Christine the Goat': 'christine.the.goat@pickware.de',
    'Antonio Kupresak': 'antonio.kupresak@pickware.de',
    'Lukas Wölfer': 'lukas.woelfer@pickware.de',
    'Giuliano De Meo': 'giuliano.de.meo@pickware.de',
};
