packages:
    - apps/*
    - packages/*

ignoredBuiltDependencies:
    - '@prisma/client'
    - prisma

catalog:
    eslint: ^9.26.0
    prettier: ^3.5.3
    typescript: ^5.8.3
    '@types/node': ^20
    '@types/eslint': ^8

catalogs:
    react18:
        react: ^18.2.0
        react-dom: ^18.2.0
        '@types/react': ^18.2.66
        '@types/react-dom': ^18.2.22
    frontend:
        vite-plugin-svgr: ^4.2.0
        clsx: ^2.1.1
        '@tanstack/react-table': ^8.20.5
        tailwind-merge: ^2.4.0
        tailwindcss-animate: ^1.0.7
        react-i18next: ^14.1.1
        lucide-react: ^0.451.0
        tailwindcss: ^3.4.13
