packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@prisma/client'
  - prisma

catalog:
  eslint: ^9.26.0
  typescript: ^5.8.3
  '@types/node': ^20
  '@types/eslint': ^8
  '@types/jest': ^29.5.14
  '@types/uuid': ^10.0.0
  '@typescript-eslint/eslint-plugin': ^8.31.1
  '@typescript-eslint/parser': ^8.31.1
  typescript-eslint: ^8.31.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  globals: ^15.14.0
  axios: ^1.7.7
  uuid: ^10.0.0
  '@biomejs/biome': ^2.3.2
  class-transformer: ^0.5.1
  class-validator: ^0.14.1
  openskill: ^4.1.0

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    '@types/react': ^18.3.12
    '@types/react-dom': ^18.3.1
  frontend:
    vite-plugin-svgr: ^4.2.0
    clsx: ^2.1.1
    '@tanstack/react-table': ^8.20.5
    '@tanstack/react-form': ^1.12.4
    tailwind-merge: ^2.4.0
    tailwindcss-animate: ^1.0.7
    react-i18next: ^14.1.1
    lucide-react: ^0.451.0
    tailwindcss: ^3.4.13

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@sentry-internal/node-cpu-profiler'
  - '@swc/core'
  - esbuild
  - sharp
