name: Build and Push Docker Image

on:
    push:
        branches:
            - task/add-deployment
        tags:
            - "v*" # Only run on version tags like v1.0.0

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Log in to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  tags: jonathanschad/react-nestjs-boilerplate:latest # Replace with your DockerHub username and image name
                  push: true

            # Optionally, tag the image with the Git commit SHA
            # - name: Tag with Git SHA
            #   if: github.ref == 'refs/heads/main'
            #   run: |
            #     docker tag yourusername/yourimage:latest yourusername/yourimage:${{ github.sha }}
            #     docker push yourusername/yourimage:${{ github.sha }}
