name: Bump Patch Version

on:
    push:
        branches:
            - main

permissions:
    contents: write # Allow the GitHub Actions bot to push changes

jobs:
    bump-version:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Get Latest Commit Message
              id: get_commit_msg
              run: echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

            - name: Skip Version Bump if Commit Message Contains '[skip ci]'
              if: ${{ contains(env.commit_message, '[skip ci]') }}
              run: echo "Skipping version bump for version bump commit"

            - name: Bump Patch Version - Client and Server
              if: ${{ !contains(env.commit_message, '[skip ci]') }}
              run: |
                  # Bump the patch version in both client and server package.json files
                  cd client 
                  npm version patch --no-git-tag-version
                  cd ../server 
                  npm version patch --no-git-tag-version
                  cd .. 
                  ls -la

                  # Stage both package.json files
                  git add ./client/package.json ./server/package.json

                  # Commit the changes with a combined message
                  NEW_VERSION=$(node -p "require('./server/package.json').version")
                  # Configure Git author for the commit
                  git config user.name "github-actions[bot]"
                  git config user.email "actions@github.com"
                  git commit -am "ci: bump version to $NEW_VERSION [skip ci]"
              env:
                  GIT_COMMITTER_NAME: github-actions
                  GIT_COMMITTER_EMAIL: actions@github.com

            - name: Push Changes and Create Tag
              if: ${{ !contains(env.commit_message, '[skip ci]') }}
              env:
                  GIT_COMMITTER_NAME: github-actions
                  GIT_COMMITTER_EMAIL: actions@github.com
              run: |
                  # Configure Git author for the commit
                  git config user.name "github-actions[bot]"
                  git config user.email "actions@github.com"

                  # Push the commit to main
                  git push origin main

                  # Create and push a new tag with the new version
                  git tag "v$NEW_VERSION"
                  git push origin "v$NEW_VERSION"
